package com.hiapps.hinotes.ui.icons

import androidx.annotation.DrawableRes
import com.hiapps.hinotes.R

/**
 * Material Symbols Rounded glyphs, one vector drawable each.
 *
 * Generated by tools/gen_symbol_vectors.py from the Material Symbols Rounded font that
 * also produced the app icon; do not edit by hand.
 */
object Symbols {
    @DrawableRes val Archive: Int = R.drawable.sym_archive
    @DrawableRes val ArrowBack: Int = R.drawable.sym_arrow_back
    @DrawableRes val Bookmarks: Int = R.drawable.sym_bookmarks
    @DrawableRes val Box: Int = R.drawable.sym_box
    @DrawableRes val Check: Int = R.drawable.sym_check
    @DrawableRes val CheckBoxOutlineBlank: Int = R.drawable.sym_check_box_outline_blank
    @DrawableRes val ChevronRight: Int = R.drawable.sym_chevron_right
    @DrawableRes val Close: Int = R.drawable.sym_close
    @DrawableRes val Colors: Int = R.drawable.sym_colors
    @DrawableRes val Contrast: Int = R.drawable.sym_contrast
    @DrawableRes val DarkMode: Int = R.drawable.sym_dark_mode
    @DrawableRes val Delete: Int = R.drawable.sym_delete
    @DrawableRes val Download: Int = R.drawable.sym_download
    @DrawableRes val Edit: Int = R.drawable.sym_edit
    @DrawableRes val Face: Int = R.drawable.sym_face
    @DrawableRes val Fingerprint: Int = R.drawable.sym_fingerprint
    @DrawableRes val FormatBold: Int = R.drawable.sym_format_bold
    @DrawableRes val FormatItalic: Int = R.drawable.sym_format_italic
    @DrawableRes val FormatSize: Int = R.drawable.sym_format_size
    @DrawableRes val GridView: Int = R.drawable.sym_grid_view
    @DrawableRes val Info: Int = R.drawable.sym_info
    @DrawableRes val KeyboardArrowDown: Int = R.drawable.sym_keyboard_arrow_down
    @DrawableRes val Language: Int = R.drawable.sym_language
    @DrawableRes val List: Int = R.drawable.sym_list
    @DrawableRes val Lock: Int = R.drawable.sym_lock
    @DrawableRes val OpenInNew: Int = R.drawable.sym_open_in_new
    @DrawableRes val Palette: Int = R.drawable.sym_palette
    @DrawableRes val Password: Int = R.drawable.sym_password
    @DrawableRes val Redo: Int = R.drawable.sym_redo
    @DrawableRes val Save: Int = R.drawable.sym_save
    @DrawableRes val Search: Int = R.drawable.sym_search
    @DrawableRes val SelectAll: Int = R.drawable.sym_select_all
    @DrawableRes val Sell: Int = R.drawable.sym_sell
    @DrawableRes val Settings: Int = R.drawable.sym_settings
    @DrawableRes val Share: Int = R.drawable.sym_share
    @DrawableRes val Sort: Int = R.drawable.sym_sort
    @DrawableRes val TextFields: Int = R.drawable.sym_text_fields
    @DrawableRes val Undo: Int = R.drawable.sym_undo
    @DrawableRes val Update: Int = R.drawable.sym_update
    @DrawableRes val Upload: Int = R.drawable.sym_upload
    @DrawableRes val ViewList: Int = R.drawable.sym_view_list
    @DrawableRes val Visibility: Int = R.drawable.sym_visibility
}
