package com.hinotes.app.ui.icons

/**
 * Codepoints into the bundled Material Symbols Rounded font
 * (res/font/material_symbols_rounded.ttf, FILL=0 outlined, weight 400).
 *
 * Generated by tools/gen_symbols.py - do not edit by hand.
 */
internal object Symbols {
    const val Add: Int = 0xE145 // add
    const val AddPhotoAlternate: Int = 0xE43E // add_photo_alternate
    const val Archive: Int = 0xE149 // archive
    const val ArrowBack: Int = 0xE5C4 // arrow_back
    const val Bookmarks: Int = 0xE98B // bookmarks
    const val Box: Int = 0xF5A4 // box
    const val Check: Int = 0xE668 // check
    const val CheckBoxOutlineBlank: Int = 0xE835 // check_box_outline_blank
    const val ChevronRight: Int = 0xE5CC // chevron_right
    const val Close: Int = 0xE5CD // close
    const val Colors: Int = 0xE997 // colors
    const val Contrast: Int = 0xEB37 // contrast
    const val DarkMode: Int = 0xE51C // dark_mode
    const val Delete: Int = 0xE92E // delete
    const val Download: Int = 0xF090 // download
    const val Edit: Int = 0xF097 // edit
    const val Face: Int = 0xF008 // face
    const val Fingerprint: Int = 0xE90D // fingerprint
    const val FormatBold: Int = 0xE238 // format_bold
    const val FormatItalic: Int = 0xE23F // format_italic
    const val FormatSize: Int = 0xE245 // format_size
    const val Info: Int = 0xE88E // info
    const val KeyboardArrowDown: Int = 0xE313 // keyboard_arrow_down
    const val Language: Int = 0xEA07 // language
    const val List: Int = 0xE896 // list
    const val Lock: Int = 0xE899 // lock
    const val MoreVert: Int = 0xE5D4 // more_vert
    const val NoteAdd: Int = 0xE89C // note_add
    const val OpenInNew: Int = 0xE89E // open_in_new
    const val Palette: Int = 0xE40A // palette
    const val Password: Int = 0xF042 // password
    const val Redo: Int = 0xE15A // redo
    const val Save: Int = 0xE161 // save
    const val Search: Int = 0xEF7A // search
    const val Sell: Int = 0xF05B // sell
    const val Settings: Int = 0xE8B8 // settings
    const val Share: Int = 0xE80D // share
    const val Sort: Int = 0xE164 // sort
    const val TextFields: Int = 0xE262 // text_fields
    const val Title: Int = 0xE264 // title
    const val Undo: Int = 0xE166 // undo
    const val Update: Int = 0xE923 // update
    const val Upload: Int = 0xF09B // upload
    const val Visibility: Int = 0xE8F4 // visibility
}
