#!/usr/bin/env python
"""Generate `AccentPalettes.kt`: the Material 3 colour schemes for every accent choice.

Each accent is a seed colour run through the official material-color-utilities implementation,
which is the same HCT maths Material Theme Builder and Android's dynamic colour use. Tonal Spot
is the variant Android itself derives a theme with, so an accent chosen here and an accent taken
from the wallpaper are built the same way; the grey accent uses Monochrome, which is the MD3
variant for a scheme without colour.

Run:  python tools/gen_accents.py
"""
import os
from pathlib import Path

import material_color_utilities as m

# This file lives in <repo>/tools, so the repository is one directory up.
REPO = Path(__file__).resolve().parents[1]
OUT = str(REPO / "app/src/main/java/com/hiapps/hinotes/ui/theme/AccentPalettes.kt")

# enum entry -> (seed, MD3 variant). "Light purple" is not generated: it is the design's own
# hand-specified palette and lives in ColorTokens.kt.
ACCENTS = [
    ("TeaGreen", "#6F8F57", m.Variant.TONALSPOT),
    ("LightGray", "#9AA0A6", m.Variant.MONOCHROME),
    ("Red", "#BA1A1A", m.Variant.TONALSPOT),
    ("Blue", "#0B57D0", m.Variant.TONALSPOT),
    ("Orange", "#E8710A", m.Variant.TONALSPOT),
    ("Yellow", "#F9AB00", m.Variant.TONALSPOT),
]

# Compose ColorScheme parameter -> role in the material-color-utilities scheme.
ROLES = [
    ("primary", "primary"),
    ("onPrimary", "on_primary"),
    ("primaryContainer", "primary_container"),
    ("onPrimaryContainer", "on_primary_container"),
    ("inversePrimary", "inverse_primary"),
    ("secondary", "secondary"),
    ("onSecondary", "on_secondary"),
    ("secondaryContainer", "secondary_container"),
    ("onSecondaryContainer", "on_secondary_container"),
    ("tertiary", "tertiary"),
    ("onTertiary", "on_tertiary"),
    ("tertiaryContainer", "tertiary_container"),
    ("onTertiaryContainer", "on_tertiary_container"),
    ("error", "error"),
    ("onError", "on_error"),
    ("errorContainer", "error_container"),
    ("onErrorContainer", "on_error_container"),
    ("background", "background"),
    ("onBackground", "on_surface"),
    ("surface", "surface"),
    ("onSurface", "on_surface"),
    ("surfaceVariant", "surface_variant"),
    ("onSurfaceVariant", "on_surface_variant"),
    ("surfaceContainerLowest", "surface_container_lowest"),
    ("surfaceContainerLow", "surface_container_low"),
    ("surfaceContainer", "surface_container"),
    ("surfaceContainerHigh", "surface_container_high"),
    ("surfaceContainerHighest", "surface_container_highest"),
    ("surfaceTint", "surface_tint"),
    ("inverseSurface", "inverse_surface"),
    ("inverseOnSurface", "inverse_on_surface"),
    ("outline", "outline"),
    ("outlineVariant", "outline_variant"),
    ("scrim", "scrim"),
]

HEADER = '''package com.hiapps.hinotes.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/*
 * Generated by tools/gen_accents.py; do not edit by hand.
 *
 * Every accent is a seed colour expanded into full light and dark schemes by the official
 * material-color-utilities implementation, so each role carries the tone Material 3 prescribes:
 * primary lands on tone 40 in light and tone 80 in dark, its container on 90 and 30, the surface
 * ramp on 99 down to 90 (and 10 up to 22), and so on. Nothing here is hand-picked.
 *
 * Tonal Spot is the variant Android derives a wallpaper theme with; the grey accent uses
 * Monochrome, the MD3 variant for a scheme that carries no colour at all. The design's own
 * "Light purple" palette is not generated - it lives in ColorTokens.kt.
 */

'''


def scheme_block(name, dark, scheme):
    roles = scheme.dict()
    fn = "darkColorScheme" if dark else "lightColorScheme"
    lines = [f"internal val {name}: ColorScheme = {fn}("]
    width = max(len(param) for param, _ in ROLES)
    for param, role in ROLES:
        value = roles[role]
        argb = m.argb_from_hex(value)
        lines.append(
            "    %-*s = Color(0x%08X)," % (width, param, argb & 0xFFFFFFFF)
        )
    lines.append(")")
    return "\n".join(lines)


def main():
    blocks = []
    for name, seed, variant in ACCENTS:
        theme = m.theme_from_color(seed, 0.0, variant)
        blocks.append(f"// {name}: seed {seed}, {variant.name.lower()}")
        blocks.append(scheme_block(f"{name}Light", False, theme.schemes.light))
        blocks.append("")
        blocks.append(scheme_block(f"{name}Dark", True, theme.schemes.dark))
        blocks.append("")

    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(HEADER)
        fh.write("\n".join(blocks).rstrip() + "\n")
    print("wrote", OUT, os.path.getsize(OUT), "bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
