#!/usr/bin/env python
"""Generate HiNotes launcher icons and the in-app mark from the Material Symbols 'edit' glyph.

Outputs:
  * res/drawable/ic_logo_note.xml            - in-app About/lock mark (24dp vector)
  * res/drawable/ic_launcher_foreground.xml  - adaptive-icon foreground (108dp vector)
  * res/drawable/ic_launcher_monochrome.xml  - themed-icon (monochrome) layer
  * res/mipmap-anydpi-v26/ic_launcher{,_round}.xml
  * res/mipmap-*/ic_launcher{,_round}.png    - legacy icons for API < 26

Both the vector and the bitmap are placed by the glyph's *ink* box rather than by its em box.
The em box is 960 units but this glyph's artwork only fills 120..840 of it, so centring on the em
left the pencil visibly off-centre inside the icon; centring on the ink puts it dead centre.
"""
import os
import re

from fontTools.misc.transform import Transform
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from PIL import Image, ImageDraw, ImageFont

FONT = r"D:\tools\MaterialSymbolsRounded-var.ttf"
CODEPOINTS = r"D:\tools\MaterialSymbolsRounded.codepoints"
RES = r"D:\HiNotes\app\src\main\res"

GLYPH = "edit"
EM_UNITS = 960.0

ADAPTIVE_VIEWPORT = 108.0
ADAPTIVE_ARTWORK = 38.0          # artwork size inside the 108dp canvas
LOGO_VIEWPORT = 24.0
LOGO_ARTWORK = 24.0              # the in-app mark fills its box

DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}

BG = (74, 68, 89, 255)      # fallback mono primaryContainer
FG = (230, 224, 240, 255)   # fallback mono onPrimaryContainer

PNG_ARTWORK = 0.56          # fraction of the legacy icon the glyph occupies


def codepoint(name):
    with open(CODEPOINTS, encoding="utf-8") as fh:
        for line in fh:
            parts = line.split()
            if len(parts) == 2 and parts[0] == name:
                return int(parts[1], 16)
    raise SystemExit("codepoint not found: " + name)


def ink_bounds(name):
    font = TTFont(FONT, lazy=True)
    glyf = font["glyf"]
    glyph = glyf[name]
    glyph.recalcBounds(glyf)
    return glyph.xMin, glyph.yMin, glyph.xMax, glyph.yMax


def round_numbers(d, places=3):
    def fix(m):
        v = round(float(m.group(0)), places)
        t = ("%f" % v).rstrip("0").rstrip(".")
        return t if t not in ("", "-0") else "0"

    return re.sub(r"-?\d+\.\d+", fix, d)


def glyph_path(viewport, artwork):
    """Glyph outline centred on its ink box inside `viewport`, sizing the ink to `artwork`."""
    x0, y0, x1, y1 = ink_bounds(GLYPH)
    span = max(x1 - x0, y1 - y0)
    scale = artwork / span
    cx = (x0 + x1) / 2.0
    cy = (y0 + y1) / 2.0
    # Font space is Y-up, vector space is Y-down.
    transform = Transform(
        scale, 0, 0, -scale,
        viewport / 2.0 - cx * scale,
        viewport / 2.0 + cy * scale,
    )
    font = TTFont(FONT, lazy=True)
    pen = SVGPathPen(font.getGlyphSet())
    font.getGlyphSet()[GLYPH].draw(TransformPen(pen, transform))
    return round_numbers(pen.getCommands())


def write_drawable(name, path_data, viewport, size_dp):
    body = f'''<?xml version="1.0" encoding="utf-8"?>
<!--
  Material Symbols Rounded "{GLYPH}", centred on its ink box.
  Generated by tools/gen_icons.py; do not edit by hand.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{size_dp:g}dp"
    android:height="{size_dp:g}dp"
    android:viewportWidth="{viewport:g}"
    android:viewportHeight="{viewport:g}">
    <path
        android:fillColor="#FFFFFFFF"
        android:pathData="{path_data}" />
</vector>
'''
    out = os.path.join(RES, "drawable", name)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(body)
    print("  drawable/%-30s %4d chars" % (name, len(path_data)))


def glyph_layer(size, cp):
    """White glyph on transparent, its ink centred and occupying PNG_ARTWORK of `size`.

    The ink's position is *measured* rather than derived: the glyph is first drawn onto a scratch
    canvas at a known origin, the resulting ink box is read back, and the placement is solved from
    it. `ImageFont.getbbox` reports a box based on the font's layout extent rather than the
    artwork, which left the pencil about 6% high.
    """
    x0, y0, x1, y1 = ink_bounds(GLYPH)
    ink_units = max(x1 - x0, y1 - y0)
    target_ink = size * PNG_ARTWORK
    # FreeType sizes by em, so ask for an em whose ink lands on the target.
    font_px = max(8, int(round(target_ink * EM_UNITS / ink_units)))
    font = ImageFont.truetype(FONT, font_px)
    text = chr(cp)

    pad = font_px * 2
    scratch = Image.new("L", (pad + font_px * 2, pad + font_px * 2), 0)
    ImageDraw.Draw(scratch).text((pad, pad), text, font=font, fill=255)
    box = scratch.getbbox()
    if box is None:
        return Image.new("RGBA", (size, size), (0, 0, 0, 0))

    ink_w, ink_h = box[2] - box[0], box[3] - box[1]
    # Where the ink started relative to the draw origin.
    dx = box[0] - pad
    dy = box[1] - pad

    layer = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    ImageDraw.Draw(layer).text(
        ((size - ink_w) / 2 - dx, (size - ink_h) / 2 - dy),
        text,
        font=font,
        fill=(255, 255, 255, 255),
    )
    return layer


def compose(glyph, size, circular):
    ss = 4
    canvas = Image.new("RGBA", (size * ss, size * ss), (0, 0, 0, 0))
    draw = ImageDraw.Draw(canvas)
    if circular:
        draw.ellipse([0, 0, size * ss - 1, size * ss - 1], fill=BG)
    else:
        draw.rounded_rectangle(
            [0, 0, size * ss - 1, size * ss - 1], radius=size * ss * 0.22, fill=BG
        )
    big = glyph.resize((size * ss, size * ss), Image.LANCZOS)
    tinted = Image.new("RGBA", big.size, FG)
    tinted.putalpha(big.getchannel("A"))
    canvas.alpha_composite(tinted)
    return canvas.resize((size, size), Image.LANCZOS)


def main():
    cp = codepoint(GLYPH)
    x0, y0, x1, y1 = ink_bounds(GLYPH)
    print("glyph %s U+%04X  ink x[%d..%d] y[%d..%d]  em %.0f"
          % (GLYPH, cp, x0, x1, y0, y1, EM_UNITS))
    print("ink centre (%.1f, %.1f) vs em centre (%.0f, %.0f)"
          % ((x0 + x1) / 2, (y0 + y1) / 2, EM_UNITS / 2, EM_UNITS / 2))
    print()

    write_drawable("ic_logo_note.xml", glyph_path(LOGO_VIEWPORT, LOGO_ARTWORK), LOGO_VIEWPORT, 24.0)
    adaptive = glyph_path(ADAPTIVE_VIEWPORT, ADAPTIVE_ARTWORK)
    write_drawable("ic_launcher_foreground.xml", adaptive, ADAPTIVE_VIEWPORT, ADAPTIVE_VIEWPORT)
    write_drawable("ic_launcher_monochrome.xml", adaptive, ADAPTIVE_VIEWPORT, ADAPTIVE_VIEWPORT)

    anydpi = os.path.join(RES, "mipmap-anydpi-v26")
    os.makedirs(anydpi, exist_ok=True)
    adaptive_xml = '''<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
'''
    for name in ("ic_launcher.xml", "ic_launcher_round.xml"):
        with open(os.path.join(anydpi, name), "w", encoding="utf-8", newline="\n") as fh:
            fh.write(adaptive_xml)
    print("  mipmap-anydpi-v26/ic_launcher{,_round}.xml")

    glyph = glyph_layer(max(DENSITIES.values()) * 2, cp)
    for bucket, px in DENSITIES.items():
        out = os.path.join(RES, f"mipmap-{bucket}")
        os.makedirs(out, exist_ok=True)
        compose(glyph, px, False).save(os.path.join(out, "ic_launcher.png"))
        compose(glyph, px, True).save(os.path.join(out, "ic_launcher_round.png"))
    print("  mipmap-*/ic_launcher{,_round}.png at %d densities" % len(DENSITIES))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
